---
db_user: postgres
db_password: postgres
db_name_development: railsws_development
db_name_test: railsws_test
db_host: localhost

pg_version: 9.3
pg_conf: /etc/postgresql/{{pg_version}}/main/postgresql.conf
pg_hba: /etc/postgresql/{{pg_version}}/main/pg_hba.conf
pg_dir: /var/lib/postgresql/{{pg_version}}/main

project_root: /vagrant

rbenv_root: /home/vagrant/.rbenv
ruby_version: 2.3.0
ruby_build_root: /home/vagrant/.rbenv/plugins/ruby-build