---
db_user: postgres
db_password: postgres
db_name_development: railsws_development
db_name_test: railsws_test
db_host: localhost

pg_version: 9.3
pg_conf: /etc/postgresql/{{pg_version}}/main/postgresql.conf
pg_hba: /etc/postgresql/{{pg_version}}/main/pg_hba.conf
pg_dir: /var/lib/postgresql/{{pg_version}}/main

project_root: /vagrant

rbenv_root: /home/vagrant/.rbenv
ruby_version: 2.3.0
ruby_build_root: /home/vagrant/.rbenv/plugins/ruby-build


# https://github.com/nicolai86/ansible-phantomjs

# phantomjs_version is used to check against the currently installed phantomjs
# version. A perfect version match is required to skip the installation.
phantomjs_version: "2.1.1"

# phantomjs_url defines which binary to download & instract.
phantomjs_url: "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"

# phantomjs_install_libfontconfig is a dependency for phantomjs on Debian 7.
# See https://github.com/ariya/phantomjs/issues/10904 for more details.
phantomjs_install_libfontconfig: true
