---
- name: postgresql | Be sure to have the right LC_ALL env var
  lineinfile: dest=/etc/environment line=LC_ALL="en_US.utf-8"

- name: postgresql | Reload /etc/environement
  shell: bash -lc "source /etc/environment"

- name: postgresql | ensure python-psycopg2 is present
  apt: pkg=python-psycopg2 state=present

- name: postgresql | ensure postgresql is installed
  apt: pkg=postgresql state=present

- name: postgresql | Edit postgresql.conf to change listen address to '*'
  command: sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" "{{pg_conf}}"
  sudo: yes

- name: postgresql | Append to pg_hba.conf to add password auth
  lineinfile: dest={{pg_hba}} line="host    all             all             all                     md5"
  sudo: yes

- name: postgresql | Explicitly set default client_encoding
  lineinfile: dest={{pg_conf}} line="client_encoding = utf8"
  sudo: yes

- name: postgresql | Restart so that all new config is loaded
  command: service postgresql restart
  sudo: yes

- name: postgresql | ensure postgresql start at boot
  service: name=postgresql enabled=yes state=started

- name: postgresql | ensure database for development exists
  postgresql_db: "name={{ db_name_development }} state=present"
  sudo_user: postgres

- name: postgresql | ensure user exists for development database
  postgresql_user: "db={{ db_name_development }} name={{ db_user }} password={{ db_password }}"
  sudo_user: postgres

- name: postgresql | ensure database for test exists
  postgresql_db: "name={{ db_name_test }} state=present"
  sudo_user: postgres

- name: postgresql | ensure user exists for test database
  postgresql_user: "db={{ db_name_test }} name={{ db_user }} password={{ db_password }}"
  sudo_user: postgres
