---
- name: ruby | install build depends
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - build-essential
    - git
    - libpq-dev
    - libreadline-dev
    - libssl-dev
    - libffi-dev

- name: ruby | update rbenv repo
  git: accept_hostkey=true repo=git://github.com/sstephenson/rbenv.git dest={{ rbenv_root }} version=v0.4.0
  sudo: no

- name: ruby | add rbenv initialization to profile
  template: src=../templates/rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755

- name: ruby | create ruby-build folder
  command: mkdir -p {{ ruby_build_root }}
  sudo: no

- name: ruby | update ruby-build repo
  git: accept_hostkey=true repo=git://github.com/sstephenson/ruby-build.git dest={{ ruby_build_root }}
  sudo: no

- name: ruby | install ruby-build
  command: ./install.sh chdir={{ ruby_build_root }}

- name: ruby | check ruby ruby_version installed
  shell: bash -lc "RBENV_ROOT={{rbenv_root}} rbenv versions | grep {{ruby_version}}"
  register: ruby_installed
  ignore_errors: yes
  sudo: no

- name: ruby | install ruby {{ ruby_version }}
  shell: bash -lc "RBENV_ROOT={{rbenv_root}} rbenv install {{ruby_version}}"
  when: ruby_installed|failed
  sudo: no

- name: ruby | set global ruby {{ruby_version}}
  shell: bash -lc "RBENV_ROOT={{rbenv_root}} rbenv global {{ruby_version}}"
  when: ruby_installed|failed
  sudo: no

- name: ruby | rehash
  shell: bash -lc "RBENV_ROOT={{rbenv_root}} rbenv rehash"
  when: ruby_installed|failed
  sudo: no

- name: ruby | set gemrc
  copy: src=../files/gemrc dest=/home/vagrant/.gemrc owner=vagrant group=vagrant mode=0644
  sudo: no

- name: ruby | install Bundler
  shell: bash -lc "gem install bundler"
  sudo: no

- name: ruby | rehash after installing Bundler
  shell: bash -lc "RBENV_ROOT={{rbenv_root}} rbenv rehash"
  sudo: no
